# Generated by Django 6.0.3 on 2026-03-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
